[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

############################
# SYSLOG INPUT (GNS3)
############################

[INPUT]
    Name   syslog
    Mode   udp
    Listen 0.0.0.0
    Port   514
    Tag    gns3.logs

############################
# WRAP FOR PRODUCER
############################

[FILTER]
    Name lua
    Match *
    script wrap.lua
    call wrap_logs

############################
# OUTPUT → PRODUCER
############################

[OUTPUT]
    Name http
    Match *
    Host producer
    Port 4318
    URI /v1/logs
    Format json
    Header Content-Type application/json